### ISSUE TITLE
Merge Item operations into Operations table

### ISSUE THREAD

**Issue by hichamlahlou** [frePPLe/frePPLe#105]
There could be issues if the declared item/location combination is different in Item Operations and in item Materials. It is better to add into operations table the produced item, priority and effective start/end dates.

**Comment by hichamlahlou** [comment]
Checked that the item_id is not mandatory in the operation table => OK
The effective_start and effective_end dates are not respected.
In the manufacturing_demo fixture :

update operation 
set effective_start = to_date('01/02/2016','DD/MM/YYYY'),
effective_end = to_date('01/02/2018','DD/MM/YYYY')
where name = 'Saw chair leg'

select startdate, enddate, quantity from operationplan where status = 'proposed' and type = 'MO'
and operation_id = 'Saw chair leg'
order by startdate

"2016-01-15 16:16:40+01";"2016-01-20 05:26:40+01";367.0000
"2016-01-21 19:40:00+01";"2016-01-22 00:40:00+01";30.0000
"2016-01-22 00:40:00+01";"2016-01-22 01:20:00+01";4.0000
"2016-01-22 01:20:00+01";"2016-01-22 06:20:00+01";30.0000
"2016-01-22 06:20:00+01";"2016-01-22 20:40:00+01";86.0000

**Comment by jdetaeye** [comment]
Works for me.

But there is an issue with the solver on the case: Instead of delaying the 'saw chair leg' operation a feasible time, it plans the demand short.  Putting this in a different waffle.
When you run with plan.loglevel =3 you get output:

      Operation 'Assemble chair' is asked: 26  2016-02-29T00:00:00
      Resource 'assembly line' is asked: 1  2016-02-25T22:00:00 / 2016-02-27T00:00:00
      Resource 'assembly line' answers: 1  2016-02-27T00:00:00
       Resource 'operators' is asked: 2  2016-02-25T22:00:00 / 2016-02-27T00:00:00
       Resource 'operators' answers: 2  2016-02-27T00:00:00
      Buffer 'chair leg @ factory' is asked: 104  2016-02-25T22:00:00
       Alternate operation 'Replenish chair leg @ factory' is asked: 74  2016-02-25T22:00:00
       Alternate operation 'Replenish chair leg @ factory' answers: 0  2030-12-31T00:00:00  1800  12       <<<<<<< WRONG, answer should be the effective start of the operation
      Buffer 'chair leg @ factory' answers: 30  2030-12-31T00:00:00  2100  12
      Buffer 'cushion @ factory' is asked: 7  2016-02-25T22:00:00
      Buffer 'cushion @ factory' answers: 7  2030-12-31T00:00:00  2240  12
      Buffer 'screws @ factory' is asked: 28  2016-02-25T22:00:00
      Buffer 'screws @ factory' answers: 28  2030-12-31T00:00:00  2268  12
      Operation 'Assemble chair' answers: 7  2030-12-31T00:00:00  2275  12
      Operation 'Assemble chair' is asked: 19  2016-02-29T00:00:00
      Resource 'assembly line' is asked: 1  2016-02-26T05:00:00 / 2016-02-27T00:00:00
