### ISSUE TITLE
Don't install Odoo automatically during make

### ISSUE THREAD

**Issue by sprauerc** [frePPLe/frePPLe#106]
Odoo is currently installed automatically during make.

could this be an option ?

**Comment by jdetaeye** [comment]
The odoo app in frepple is commented out by default:
https://github.com/frePPLe/frePPLe/blob/master/contrib/django/djangosettings.py#L229

We are not installing any odoo software in any case - we have no code dependency on their code.

Can you elaborate on your suggestion?
