### ISSUE TITLE
Backup the database option not adapted to cloud deployment

### ISSUE THREAD

**Issue by hichamlahlou** [frePPLe/frePPLe#109]
When a user exports a dump of the database, the file is written on the server location. I think we should remove this option for cloud installation.

**Comment by jdetaeye** [comment]
Files to update for this are   contrib/django/freppledb/execute/templates/execute.html and  contrib/django/freppledb/execute/views.py
Just a matter of removing some sections from the code on the cloud branch.

**Comment by hichamlahlou** [comment]
There are open points here :
Why on my local instance I can't see for instance the webservice menu ?
The "Import/Export data files in folder" doesn't work locally too. and I think it makes sense to remove it too, no ?

**Comment by jdetaeye** [comment]
>>Why on my local instance I can't see for instance the webservice menu ?

Depends on the parameter plan.webservice

>>The "Import/Export data files in folder" doesn't work locally too. 

Depends on the FILEUPLOADFOLDER setting of the database in djangosettings.

>> ... and I think it makes sense to remove it too, no ?

I'ld like to keep it available. We can configure an FTP folder on our server (company specific of course), and some customers can put their frepple datafiles in there or pick up data files from it.
