### ISSUE TITLE
update fixutres in community edition with output tables

### ISSUE THREAD

**Issue by jdetaeye** [frePPLe/frePPLe#122]
The fixtures should include the output table, just as they do in the enterprise edition.
The current mismatch of both files makes in impossible to keep them in sync.

**Comment by jdetaeye** [comment]
Bonus - migrate the json dump script to the proper Python framework...

**Comment by hichamlahlou** [comment]
done for demo and manufacturing_demo

**Comment by jdetaeye** [comment]
The suboperations are left out from the fixture now...  You're not dumping them in your script?

Unit test spotted the error.

**Comment by hichamlahlou** [comment]
Correct table suboperation is missing, I will add it

**Comment by jdetaeye** [comment]
Common.scenario table should also be excluded from the fixtures

**Comment by hichamlahlou** [comment]
done

**Comment by hichamlahlou** [comment]
Table out_problem is missing, the manufacturing dataset has ne late orders when clicking from the late orders widget.

**Comment by jdetaeye** [comment]
One more issue for the fixtures in the Enterprise Edition: The field "operationplan.forecast_id" is empty.   For shipping operationplans of type DLVR for forecast that's used.   As a result we get "Empty demand field" errors when the data is loaded.

**Comment by hichamlahlou** [comment]
done
