### ISSUE TITLE
correct handling of input&output records in operationplanmaterial and operationplanresource tables

### ISSUE THREAD

**Issue by jdetaeye** [frePPLe/frePPLe#138]

**Comment by hichamlahlou** [comment]
1) Add a status column in the operationplanmaterial and operationplanresource tables. The status column can be either proposed or confirmed. These two tables are input/output tables => Should we make them visible in the GUI ?
2) In the operationplanmaterial, replace column buffer by item and location
3) When running a plan, all the proposed records of these two tables should be deleted in the preprocessing.
4) All the confirmed records (which represent the WIP), should be taken into consideration by the c++ engine in the way that the associated operation (which must also have a confimed status) should see its quantity possibly decreased based on the WIP.

**Comment by hichamlahlou** [comment]
Tests performed
1) Operationplanmaterial confirmed while operationplan is still in proposed status
-> The operationplanmaterial record is changed back to the proposed status by the plan workflow (actually a new record is created while old one is deleted)
2) Operationplanmaterial confirmed with half the quantity  while operationplan is still in proposed status (actually a new record is created while old one is deleted)
-> The operationplanmaterial record is changed back to the proposed status and to the original quantity by the plan workflow
3) Operationplanmaterial confirmed with another date  while operationplan is still in proposed status
-> The operationplanmaterial record is changed back to the proposed status and to the original dateby the plan workflow (actually a new record is created while old one is deleted)
4) operationplan record confirmed, operationplanmaterial records left in proposed status
PROBLEM : 2 records in operationplanmaterial with the same date/quantity and both in confirmed status.
CORRECTION: Deleting all the proposed records of the operationplanmaterial in the export_database_plan.py 
AFTER CORRECTION : One record of type confirmed is left in the operationplanmaterial table.
5) Running the plan two times in a row when both operationplan and operationplanmaterial are confirmed
-> ok, both records are left unchanged
6) Operationplan confirmed, operationplanmaterial confirmed with half the quantity, no date change
-> ok, the plan is proposing another record in proposed mode with missing quantity.
7) Running twice the workflow after 6)
-> ok, no change
8) Operationplan confirmed, operationplanmaterial confirmed with a date moved one week forward, no quantity changed
-> the plan is proposing another record for the original date quantity. ok (the plan decided not to wait for that confirmed PO)
