### ISSUE TITLE
load with skill not imported with xml

### ISSUE THREAD

**Issue by mfatihercik** [frePPLe/frepple#148]
I can't  import load with skill from xml. skill and load created but load didn't have skill.

**Comment by jdetaeye** [comment]
Can you provide an example of your XML file?

Our unit test is at https://github.com/frePPLe/frePPLe/blob/master/test/skills/skills.xml and it is passing.

**Comment by mfatihercik** [comment]
is your test for vrsion 4 or 3.2 ?.

I used version 3.2. 

xml attached

[loadwithskill.txt](https://github.com/frePPLe/frePPLe/files/732371/loadwithskill.txt)
