### ISSUE TITLE
drilldowns in the demand report not showing expected results

### ISSUE THREAD

**Issue by jdetaeye** [frePPLe/frepple#149]
SQL queries for the demand report are not correct any longer and need to be revised:
- not working correct for forecast
- not working correct for higher level items

The SQL will be different for enterprise and community editions.

-> not a straightforward easy fix.

**Comment by hichamlahlou** [comment]
To be discussed during the Friday call but my concern is that there is an arrow when the item is an aggregated item (All Items for instance in the distribution model) and clicking on the arrow gives nothing because there is no forecast record for that item.
Otherwise, the quantities seem to be ok
