### ISSUE TITLE
missing/wrong delay field in downloading PO/MO/Distribution Order

### ISSUE THREAD

**Issue by ccandito** [frePPLe/frePPLe#151]
Dear All,
the delay field is missing in all the three CVS files exported automatically as planning run result, that's the three following files: distributionorder.csv, purchaseorder.csv and manufacturingorder.csv 
don't have the delay field in them.

In downloading manually from the screen as either excel or cvs file, the delay field is populated with an inconsistent value; e.g. for a delay of 14:38:28 on the screen (hence more than 14 hours), we have in excel the amount -2366492.... as duration shoud be 2366492/(60*60*24)= 27,39 days

Regards
claudio candito

**Comment by jdetaeye** [comment]
Things to fix:
- add delay field to csv exports
- duration formatter doesn't show negative values correctly

**Comment by jdetaeye** [comment]
Comment from Cluadio:
>>unfortunately there is still an issue.
>>For delays smaller than 1 day, e.g. 6 hours that's 6:00:00, the excel cell is populated with a wrong negative value.
>>For more than 1 day, all seems to be fine.
