### ISSUE TITLE
import from folder - secure

### ISSUE THREAD

**Issue by jdetaeye** [frePPLe/frePPLe#157]
running SQLs are OK, as long as the user is controlled.

Currently it runs as same user as the web app, which means full access

**Comment by jdetaeye** [comment]
SQL file execution is now enabled when a role is specified in djangosettings.py. By default it is deactivated.

With this role-restriction in place it is now safe & ok to put in community edition and updated the documentation.

**Comment by hichamlahlou** [comment]
Might have to be reworked as the copy command is not accessible.
psql command ?

**Comment by hichamlahlou** [comment]
Added some code to handle the .cpy files.
The file must have some conventions :
the file must have the table name as basename : E.g: demand.1.cpy
the file must be comma separated
the first line must contain the columns comma separated (these are used when building the copy_expert string)

**Comment by jdetaeye** [comment]
Added .cpy files to the execute screen.
I had to assure the lastmodified field is included as part of the data, otherwise the import fails.
