### ISSUE TITLE
relable price to cost

### ISSUE THREAD

**Issue by jdetaeye** [frePPLe/frePPLe#158]

**Comment by jdetaeye** [comment]
UI changes:  Joao
C++ engine change: Hicham

**Comment by jranita** [comment]
UI, migration and Doc changes DONE.

**Comment by hichamlahlou** [comment]
Warning : merging master branch to enterprise branch will require changes specific to the enterprise version.

**Comment by jranita** [comment]
I already did changes on my Enterprise local but I will only submit after the merge (after community passes the tests).
