### ISSUE TITLE
better and shorter breadcrumb trail

### ISSUE THREAD

**Issue by jdetaeye** [frePPLe/frepple#168]
Current different tabs of the same detailed entity show as different crumbs.
It would be better to display those as a single crumb on the object.

**Comment by jdetaeye** [comment]
![image](https://cloud.githubusercontent.com/assets/5219207/24139898/3fd3dc1e-0e1e-11e7-9a92-a93e937292e4.png)

**Comment by jranita** [comment]
Looks good, tested going to the same location starting from different reports, and visiting different tabs for that location (no tab info showed on breadcrumb as intended).
