### ISSUE TITLE
refactor calendar bucket internal data

### ISSUE THREAD

**Issue by jdetaeye** [frePPLe/frePPLe#174]
Offset data structure is pretty greedy on memory on Linux.

**Comment by jdetaeye** [comment]
Memory usage of MTS model should be lower now.   Can you run a comparison in your linux VM of the process size just after reading the calendar buckets from the db?

**Comment by hichamlahlou** [comment]
BEFORE:
before adding calendar buckets, memory size is peanuts
after adding calendar buckets, memory is 2.930G

AFTER:

**Comment by jdetaeye** [comment]
missing part of comment?

**Comment by hichamlahlou** [comment]
No was performing the second part of the test :-)

After
2.7G => 230 MB saved.

**Comment by jdetaeye** [comment]
Much less gains than I expected :-(

**Comment by jdetaeye** [comment]
will investigate a bit deeper on my end

**Comment by jdetaeye** [comment]
The bulk of the memory increase goes into the cursor, not the frepple engine.  We'll see the same when the number of records to read goes really high.

Django 1.11 supports "server side cursors" that promise to be more memory efficient when reading results of large queries.

**Comment by jdetaeye** [comment]
Quick test on memory size after reading calendar buckets:   1.3GB instead of 2.7GB
