### ISSUE TITLE
ability to model working hours per operation/resource rather than per location

### ISSUE THREAD

**Issue by jdetaeye** [frePPLe/frepple#178]
Currently working hours are associated with a location.
Being able to assign different working hours within the same location comes up frequently as a n enhancement request.

**Comment by hichamlahlou** [comment]
From the UI point of view :
Addition of a field 'Available' in the resource, buffer and operation tables to set a calendar.

From the logic point of view :
Any flow/load will only be possible on the resources/buffers/operations when the calendar is available. The location calendar must also be respected for these three supply chain elements meaning that we should then take the intersection of the location calendar and the supply chain element calendar. 
A problem must be reported if no available time is found

**Comment by jdetaeye** [comment]
Done: db fields added + planning engine log + unit test

To do:  revise report utilization report query + capacity export

**Comment by jdetaeye** [comment]
Ready for test.
I have verified using the engine unit test, and also by playing around in the mfg demo.

Test on 3topole dataset?

**Comment by jdetaeye** [comment]
TODO:  review behavior when no availability exists in the resource.

**Comment by hichamlahlou** [comment]
3topole : 

In the resource table, moved all the maximum calendars in the available column.

Before : 4mn50 to execute the plan
After : 12 seconds

Four orders that were not planned or planned short are now fully planned.
All open orders are now planned, which is excellent news.

However, I have the feeling (to be confirmed) that the orders are on average planned a bit later than before.
