### ISSUE TITLE
database level cascaded delete

### ISSUE THREAD

**Issue by jdetaeye** [frePPLe/frepple#179]
Deleting eg a customer is currently a pretty complex process from SQL commands: all dependent records need to be removed first.

It would be nice to use the "on delete cascade" capabilities of postgres.

Django has logic to find all related objects. But 1) when working directly with SQL commands you can't use it, and 2) it's much slower than the native database support.

SQL to delete a customer:

delete from operationplanmaterial where operationplan_id in (
  select id from operationplan 
  inner join demand on operationplan.demand_id = demand.name
  where customer_id='Customer near factory 1'
  );

delete from operationplanresource where operationplan_id in (
  select id from operationplan 
  inner join demand on operationplan.demand_id = demand.name
  where customer_id='Customer near factory 1'
  );

delete from operationplan where demand_id in (select name from demand where customer_id='Customer near factory 1');

delete from demand where customer_id='Customer near factory 1';

delete from customer where name = 'Customer near factory 1';

**Comment by jdetaeye** [comment]
Only for operationplanmaterial and operationplanresource for now. 
Other tables - leave current behavior as is.

**Comment by jdetaeye** [comment]
Estech had a related issue with the REST API.   Deleting an MO is not possible if you don't delete the operationplanmaterial and operationplanresource records - which is a very annoying anc complex.

**Comment by hichamlahlou** [comment]
Add the cascade in a migration file
Verify how it interacts with django python level delete
Look for places where we delete first opm and opr and clean that code.
Double check rest API i working fine.

**Comment by hichamlahlou** [comment]
done. Replaced the runsql in the migration file with a runpython.
