### ISSUE TITLE
ability to run all frepplectl commands from a url

### ISSUE THREAD

**Issue by jdetaeye** [frePPLe/frepple#184]
the execute screen already exposes quite a few options, but:
- doesn't cover all commands
- requires authentication through the django framework

**Comment by jdetaeye** [comment]
First prototype available on enterprise branch.

- launch a task:
      $ curl -u admin:admin  --data "constraint=15&plantype=1" http://localhost:8000/execute/api/frepple_run/
Response:
{"taskid": 49, "message": "Successfully launched task"}

- get task status of all running tasks
     $ curl -u admin:admin http://localhost:8000/execute/api/status/?id=49
{"49": {"submitted": "2017-04-20 17:17:14.166369", "finished": "2017-04-20 17:17:15.694856", "user": "admin", "started": "2017-04-20 17:17:14.767609", "status": "Failed", "arguments": "--constraint=15 --plantype=1 --env=loadplan --background", "message": "", "name": "generate plan"}}

- get status of a single task
      $ curl -u admin:admin http://localhost:8000/execute/api/status/?id=49
{"49": {"submitted": "2017-04-20 17:17:14.166369", "finished": "2017-04-20 17:17:15.694856", "user": "admin", "started": "2017-04-20 17:17:14.767609", "status": "Failed", "arguments": "--constraint=15 --plantype=1 --env=loadplan --background", "message": "'", "name": "generate plan"}}

- missing: ability to cancel a task

**Comment by jdetaeye** [comment]
Fixed issue with the check of the web service start

**Comment by hichamlahlou** [comment]
Tested more or less all the frepplectl commands.
Cannot make the status command work, according to documentation, following command is supposed to return statuses for all running ids (the one with an id as input works).

$ curl -u admin:admin http://localhost:8000/execute/api/status/
{"message": "Exception launching task: Unsupported lookup 'ne' for CharField or join on the field not permitted."}

All other frepplectl commands ran smoothly.
Updated the documentation with examples, I think that helps.

**Comment by jdetaeye** [comment]
fixed
