### ISSUE TITLE
Dynamic menus, based on prerequisite objects

### ISSUE THREAD

**Issue by jdetaeye** [frePPLe/frepple#203]
Some tables depend on others.
When the parent table is still empty, the dependent table should be completely hidden from all menus.

**Comment by jdetaeye** [comment]
implemented in community and enterprise editions

**Comment by hichamlahlou** [comment]
I have two remarks : 
Is is technically possible/simple to deactivate a menu when no item is in the menu ?
For instance when starting an empty frePPLe, there is nothing under inventory menu, I would prefer seeit deactivated :
![image](https://user-images.githubusercontent.com/14045225/27626523-add4f136-5be8-11e7-9ca3-48e2b0a0d621.png)

Second remark and probably more difficult, would it be possible to remove the separation bars when one side of the bar has no item ?

![image](https://user-images.githubusercontent.com/14045225/27626606-f8338ea4-5be8-11e7-8dcf-4ced18b3c57f.png)

**Comment by hichamlahlou** [comment]
Also, if I have an empty database (where very little menus are activated) and I import a fixture, the menus don't get updated. I need to refresh my screen to have the menus activated visible.

**Comment by jdetaeye** [comment]
>>Is is technically possible/simple to deactivate a menu when no item is in the menu ?
>> Second remark and probably more difficult, would it be possible to remove the separation bars when one side of the bar has no item ?

these are easy and valid.

>>Also, if I have an empty database (where very little menus are activated) and I import a fixture, the menus don't get updated. I need to refresh my screen to have the menus activated visible.

That's a "feature", I'm afraid.  The UI doesn't really know when a task finishes in the background (either plan generation,  emptying db, or loading db), and it doesn't automatically trigger a screen refresh.     Only solution would be a complete screen refresh rather than only a grid refresh every 5 seconds - which I don't see a valid alternative

**Comment by jdetaeye** [comment]
fixed the first issue

**Comment by hichamlahlou** [comment]
Perfect. Refresh to be discussed orally.
