### ISSUE TITLE
Gamification of the data loading wizard

### ISSUE THREAD

**Issue by jdetaeye** [frePPLe/frepple#204]
New visual layout for wizard steps, with clear paths towards goals and visibility into locked features

**Comment by jdetaeye** [comment]
Joao to work out an svg version of the layout.
Will need to be reviewed then before we then convert this in an actual widget and new wizard page.

**Comment by jranita** [comment]
SVG in common/templates/common/

**Comment by jranita** [comment]
Wizard page loaded in EnterpriseMaster.
Cockpit Widget loaded in EnterpriseMaster.

**Comment by jdetaeye** [comment]
- doc links to new window
- buffers in master data
- rename basic data

**Comment by jranita** [comment]
Inventory Plan Parameters: data-populated is True but table is empty.
