### ISSUE TITLE
HTTP upload into data folder

### ISSUE THREAD

**Issue by jdetaeye** [frePPLe/frepple#208]
In the execution screen you can see the content of the data folder.   Users of the cloud edition get an ftp-accounts to put data in the folder.

In the execution screen we should provide the capability to upload data files over the http(s) traffic.   In this way we can easily enable the upload capability without the extra burden of creating an ftp account. 
With the data volume we can expect, the scalability and performance of a ftp server vs python code the web server is limited.   We can still open the ftp protocol for customers that need it.

Upload must be possible with "basic authentication" to allow easy automation and scripting by customers.

Extra feature:
In the execution screen we can also enable display and management of subfolders.

**Comment by jranita** [comment]
Example for commandline file upload:
curl -X POST -F "component_id=inputfiles" -F "requirements.txt=@/users/frepple/documents/frepple_comunity/requirements.txt"  -F "djangosettings.py=@/users/frepple/documents/frepple_comunity/djangosettings.py" -u admin:admin http://127.0.0.1:8000/execute/uploadtofolder/
