### ISSUE TITLE
excel import messages not scrollable during import

### ISSUE THREAD

**Issue by jdetaeye** [frePPLe/frepple#222]
to make the import easily cancellable it returns something to the client for every record.
Whenever the browser receives the info, he displays it and scrolls to the bottom (using the onprogress event).   As a result the user has the feeling he can't scroll.
This automatic scrolling of the content should be made conditional: only when there is an extra line should we update the scroll position

**Comment by jranita** [comment]
If the user scrolls it will stay where the user left it.
If user does nothing it will always show last lines.

**Comment by jdetaeye** [comment]
Working, other issue is that we loose the error logs when we cancel the upload.
It should remain visible.
