### ISSUE TITLE
color of delay in sales order report

### ISSUE THREAD

**Issue by jdetaeye** [frePPLe/frepple#223]

**Comment by jdetaeye** [comment]
![image](https://user-images.githubusercontent.com/5219207/28879382-4fbaa89a-77a2-11e7-9b7a-2b9bcc5438aa.png)

Ordering by delay should give a gradual grading from yellow (>0 seconds) to red (when > 7 days).

**Comment by jranita** [comment]
A typo in the formula.
Fixed.
