### ISSUE TITLE
export to folder - autocreate export folder

### ISSUE THREAD

**Issue by jdetaeye** [frePPLe/frepple#226]
Currently the folder is not created automatically. Unless you manually create the folder (which we can't expect from first-time users) the export functionality doesn't work...

**Comment by jdetaeye** [comment]
![image](https://user-images.githubusercontent.com/5219207/29457915-d94fa1e2-841c-11e7-851f-ab570c67169f.png)
Path to the missing folder shouldn't be exposed on our cloud edition.  No real security issue, but still not as clean as it should be

**Comment by jranita** [comment]
Added code to check if the folder is there and try to create it if needed.
