### ISSUE TITLE
data file manager: add option to delete all data files

### ISSUE THREAD

**Issue by jdetaeye** [frePPLe/frepple#229]
Currently it requires a lot of clicks to remove all database files from the file upload folder.
A "delete all" button would be handy - opening the same kind of confirmation dialog.

![image](https://user-images.githubusercontent.com/5219207/29820039-59facac0-8cc3-11e7-95f0-2779944b0080.png)

**Comment by jdetaeye** [comment]
![image](https://user-images.githubusercontent.com/5219207/30370627-73f665cc-9878-11e7-99c5-228a021b00fd.png)

I ran into this issue when trying to delete the log file

**Comment by jranita** [comment]
Fixed a typo

**Comment by hichamlahlou** [comment]
I have a folder with plenty of log and csv files (more than 10). The "delete all" button returns the message that everything was deleted while 4 of them are still there. I can press as many times as I want the "delete all" button, they remain there. Pressing the delete button for one file only works.

**Comment by jranita** [comment]
By default the delete all does not delete log files.
In that case you must delete them one by one.
