### ISSUE TITLE
REST API: filter expressions not working

### ISSUE THREAD

**Issue by jdetaeye** [frePPLe/frepple#231]
A URL like http://localhost:8000/api/input/demand/?name__contains=2
should return a filtered list of demands.

**Comment by jranita** [comment]
Filter expressions are working for in input and common models for GET and DELETE requests.
For number, duration, and date fields the filters are: gt, gte, lt, lte, exact, in.
For strings: "exact, contains, in". (including the local pk)
Foreign key strings: "exact, in". ("contains" throws an error)

curl -H "Accept:application/json;indent=4" -u admin:admin "http://127.0.0.1:8000/api/input/demand/?quantity__gt=100&location=factory%202&format=json"

PATCH and PUT are different:
https://github.com/miki725/django-rest-framework-bulk/blob/master/README.rst
"Most bulk operations are pretty safe in terms of how they operate, that is you explicitly describe all requests. For example, if you need to update 3 specific resources, you have to explicitly identify those resources in the request's PUT or PATCH data. "

The user can GET the filtered data, update the data keeping the pk, and feed it to a PATCH/PUT request.

Created a test for bulk GET and DELETE filtered with "__contains".

Updated documentation, also tested and updated the curl and wget commands in the documentation.

**Comment by zipus** [comment]
> Created a test for bulk GET and DELETE filtered with "__contains".
> Updated documentation, also tested and updated the curl and wget commands in the documentation.

Sorry, can you provide where the docs show this commands? Also I can not find the patch with the test of the bulk DELETE.
My need is to GET and DELETE buffer and demand from the REST API and can not find an example.
Thanks.

**Comment by jdetaeye** [comment]
doc: https://frepple.org/docs/current/integration-guide/rest-api/index.php

online demo:  https://demo.frepple.com/api/
