### ISSUE TITLE
scenario copying only works when triggered from the production database

### ISSUE THREAD

**Issue by jdetaeye** [frePPLe/frepple#238]
Launching the task from a scenario doesn't work.

Probably an easy one to fix. Task is added to the scenario database, but copying is managed from the main database?
Better updating the task log should resolve this, and also the comment from Hicham below.

**Comment by hichamlahlou** [comment]
Would be great if we could delete the last id from the execute_log table in the target scenario. The unfinished "copying database" task is confusing to users.

**Comment by jdetaeye** [comment]
Elcam just ran into this problem today...
