### ISSUE TITLE
Plan editor not working on manufacturing model

### ISSUE THREAD

**Issue by hichamlahlou** [frePPLe/frepple#246]
stack trace :

Thread 10 "civetweb-wsock" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe37fe700 (LWP 3637)]
0x00007ffff7950e4b in frepple::LoadPlan::AlternateIterator::next (
    this=0x7fffe37f8280) at loadplan.cpp:502
502	  auto tmp = *resIter;
(gdb) where
#0  0x00007ffff7950e4b in frepple::LoadPlan::AlternateIterator::next (
    this=0x7fffe37f8280) at loadplan.cpp:502
#1  0x00007ffff795992f in frepple::utils::MetaFieldIterator<frepple::LoadPlan, frepple::LoadPlan::AlternateIterator, frepple::utils::PythonIterator<frepple::LoadPlan::AlternateIterator, frepple::Resource>, frepple::Resource>::writeField (
    this=0x7740f0, output=...) at ../../include/frepple/utils.h:8185
#2  0x00007ffff7a1c9c4 in frepple::utils::Object::writeElement (
    this=0x7fffe40166d0, o=0x7fffe37f8800, tag=..., m=frepple::utils::PLAN)
    at python.cpp:103
#3  0x00007ffff7a2b1e6 in frepple::utils::Serializer::writeElement (
    this=0x7fffe37f8800, tag=..., object=0x7fffe40166d0, 
    m=frepple::utils::PLAN) at xml.cpp:906
#4  0x00007ffff79a4dcd in frepple::utils::MetaFieldIterator<frepple::OperationPlan, frepple::OperationPlan::LoadPlanIterator, frepple::utils::PythonIterator<frepple::OperationPlan::LoadPlanIterator, frepple::LoadPlan>, frepple::LoadPlan>::writeField (this=0x778910, output=...) at ../../include/frepple/utils.h:8194
#5  0x00007ffff7a1c927 in frepple::utils::Object::writeElement (
    this=0x7fffe40066c0, o=0x7fffe37f8800, tag=..., m=frepple::utils::PLAN)
    at python.cpp:100
#6  0x00007ffff7a2b224 in frepple::utils::Serializer::writeElement (
    this=0x7fffe37f8800, tag=..., object=0x7fffe40066c0, 
    m=frepple::utils::BASE) at xml.cpp:912

**Comment by jdetaeye** [comment]
Fixed & now pushing a new cloud-live build
