### ISSUE TITLE
export to folder can't write european-style CSV files

### ISSUE THREAD

**Issue by jranita** [frePPLe/frepple#248]
Fails the frepplectl test freppledb.execute.tests.test_importexportfolder
Export is always in EN format, while import is respecting the language code.

Solution is:
1) to update the export command to retrieve the data with SQl, and then export as CSV in Python (as done in common/reports - gridreport/_generate_csv)
2) duplicate the test execute/tests/tem_importexportfolder to test the behavior also for a european language (ie switch language code as in the common/tests/ExcelTest )

**Comment by jdetaeye** [comment]
Oh dear what an old ticket.  Fixed just recently for novoferm
