### ISSUE TITLE
Show buffer report for "non-existing" buffers

### ISSUE THREAD

**Issue by jdetaeye** [frePPLe/frepple#255]
In the new data model, we don't need explicit records for all item-locations that are present in the model.
However some buffer reports don't work if there isn't such a record.  This isn't cool & nice...

**Comment by hichamlahlou** [comment]
Checked that one on manufacturing model. Truncated table buffer, executed plan and inventory report still working properly.
Based on code, only case where problem occurs is in the "if", not in the "else" where opm table is properly called.
![image](https://user-images.githubusercontent.com/14045225/60921587-28398680-a29b-11e9-9d41-580f92035dea.png)

What are the conditions to enter in the "if" ?

**Comment by jdetaeye** [comment]
duplicate of #1225
