### ISSUE TITLE
_Py_IDENTITIER Macro - support Python 3.6

### ISSUE THREAD

**Issue by iPaid** [frePPLe/frepple#269]
When I compile frepple on Win10 Visual Studio 2015 and 2017, a fault occur. VS reports that should input expression. What should I do? I've set Python environment and I don't know what should I do to solve this problem.

**Comment by jdetaeye** [comment]
Are you using python 3.5 or 3.6?   
We use 3.5 and visual studio 2015.

**Comment by jdetaeye** [comment]
Feedback:

I tried to replace “_Py_IDENTIFIER(write)” with 
“
_Py_Identifier PyId_write;
PyId_write.next = NULL;
PyId_write.string = "write";
PyId_write.object = NULL;
”
And it worked.

**Comment by iPaid** [comment]
okay, i'll try.
ty.

**Comment by jdetaeye** [comment]
Fixed with https://github.com/frePPLe/frepple/commit/c22636d5f0786a95afa5b0071121ed6abba62e79
The planning engine now compiles with both Python 3.5 and 3.6.
