### ISSUE TITLE
[Improvement] double click sales order plan gantt chart bar to jump to operation plan

### ISSUE THREAD

**Issue by szufisher** [frePPLe/frepple#273]
in the plan detail( the gantt chart) of sales order, the hint(popup when mouse stay on bar), the operation ID is not the same as operationplan (manufacture order) ID, also it is not possible to double click the bar to jump directly to the linked operationplan (MO or PO or DO), which is not user friendly

**Comment by jdetaeye** [comment]
Implemented in 6.1.0 release
