### ISSUE TITLE
Resource report: show available capacity as a line

### ISSUE THREAD

**Issue by jdetaeye** [frePPLe/frepple#276]
More intuitive and clearer than the current green bar to represent free capacity.

Current way of showing overloads in red will stay

**Comment by jdetaeye** [comment]
Implemented, and also improved the hover tooltips

**Comment by jdetaeye** [comment]
Updating doc & release notes now

**Comment by hichamlahlou** [comment]
What other graphical options do we have ?
What I had in mind was more something like this :

![image](https://user-images.githubusercontent.com/14045225/41241571-92b6efae-6d9d-11e8-9c20-60f5f475f0ba.png)

**Comment by jdetaeye** [comment]
Updated line to use 2 points:

![image](https://user-images.githubusercontent.com/5219207/41285586-ecb056cc-6e3c-11e8-9e0e-d3425b4770c8.png)

Better indeed to draw the capacity changes as steps.
