### ISSUE TITLE
create ResourceSkill Restful api 500 server error

### ISSUE THREAD

**Issue by Charlot** [frePPLe/frepple#284]
according to the api document, there is no parameter for Resource.
evenif i add 'resource' to the parameter, still 500 error,  plz check.

**call api ：**
post http://localhost:8000/api/input/resourceskill/

**parameter:**
{       
        "skill": "f",
        "effective_start": "2018-01-01T00:00:00",
        "effective_end": "2028-01-01T00:00:00",
        "priority": 1,
        "source": "PCBA Assembly Line"
   }

**result:**
Server Error (500)
There's been an error. It's been reported to the site administrators via email and should be fixed shortly. Thanks for your patience.

**Comment by jdetaeye** [comment]
Works for me now.   Issue probably fixed together with #285 - resource is a required field on resourceskill, so it's absence generates errors.
