### ISSUE TITLE
Buffer API error 500

### ISSUE THREAD

**Issue by Asiria9102** [frePPLe/frepple#296]
call post api of /api/buffer
directly return error:
Server Error (500)
There's been an error. It's been reported to the site administrators via email and should be fixed shortly. Thanks for your patience.
pls check

**Comment by hichamlahlou** [comment]
Hello, thank you for reporting this. Can you confirm which version of frePPLe you are using (community version locally installed or on the cloud) and which release ?

**Comment by jdetaeye** [comment]
Closing cold case
