### ISSUE TITLE
how to config Python and Xerces-C in Visual Studio 2015

### ISSUE THREAD

**Issue by wuyazi** [frePPLe/frepple#298]
```
The include and library directories of Python and Xerces-C will need to configured in Visual Studio.
```
how to config Python and Xerces-C in Visual Studio 2015?

**Comment by jdetaeye** [comment]
See:
* https://msdn.microsoft.com/nl-be/library/ee855621.aspx
* https://blogs.msdn.microsoft.com/vsproject/2009/06/23/inherited-properties-and-property-sheets/

The 64-bit Python installation has all you need. It is compiled with visual studio 2015.

Xerces-c binaries for visual studio 2015 are not available on the web, as far as I know.  I compiled it from  sources myself with the instructions from https://xerces.apache.org/xerces-c/build-3.html.   A bit of a pain, but it works.

Please keep in mind:
A github issue is not for asking questions.  It's for reporting issues or suggesting enhancements.

**Comment by wuyazi** [comment]
thank you, 
but i have an error when i build the project with visual studio 2015.

first, i set the `Additional Include Directories` as:
```
D:\download\xerces-c-3.1.3\src
D:\download\Python-3.6.6\PC
D:\download\Python-3.6.6\Include
..\..\include
```
when i build utils, solver, model is success.
but when i build dll project i got an error as:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1104	cannot open file 'xerces-c_static_3D.lib'	dll	C:\Users\wuyazi\Documents\frepple-master\contrib\vc\LINK	1	
```
and when i build main project i got an error as:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1104	cannot open file 'C:\Users\wuyazi\Documents\frepple-master\contrib\vc\dll\Debug\x64\output\frepple.lib'	main	C:\Users\wuyazi\Documents\frepple-master\contrib\vc\LINK	1	
```
and when i build pythonextension project i got an error as:
```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	LNK4075	ignoring '/EDITANDCONTINUE' due to '/OPT:LBR' specification	pythonextension	C:\Users\wuyazi\Documents\frepple-master\contrib\vc\pythonextension.obj	1	
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1181	cannot open input file 'C:\Users\wuyazi\Documents\frepple-master\contrib\vc\dll\Debug\x64\output\frepple.lib'	pythonextension	C:\Users\wuyazi\Documents\frepple-master\contrib\vc\LINK	1	
```
so, can you tell me how to solve this problem?
