### ISSUE TITLE
what is the django version and django-admin-bootstrapped version?

### ISSUE THREAD

**Issue by wuyazi** [frePPLe/frepple#299]
i want to know the version of django-admin-bootstrapped and django, because i got a error:
```
django-admin-bootstrapped 2.5.7 has requirement Django<1.9,>=1.8, but you'll have django 1.11.5 which is incompatible.
```

**Comment by jdetaeye** [comment]
It's a warning you can safely ignore.   On my system it doesn't stop the installation at all.

If it does on your system, you'll need to check possibilities to force installation despite the conflicts of the dependencies.

I've mentioned you before that a github ticket is for reporting bugs, and NOT for communication on any issues you happen to run into when installing or using frepple. Please use the user forum for that.
