### ISSUE TITLE
Variable 'website' is not defined in frepple.js

### ISSUE THREAD

**Issue by jfromell** [frePPLe/frepple#310]
On a fresh install of frepple 4.4.2 community edition, upon visiting /wizard the page is blank and the console logs an error claiming that `website` is undefined. Investigating the issue led to frepple.js and indeed, the variable is not even defined in the scope for the function nor anywhere in the script.

**Comment by jdetaeye** [comment]
It's a bug indeed that has been fixed in the meantime: https://github.com/frePPLe/frepple/commit/19215a0e696d99ff107aba71f414894d0d04c89b
