### ISSUE TITLE
cookbook for resource efficiency

### ISSUE THREAD

**Issue by jdetaeye** [frePPLe/frepple#312]
This modeling topic comes back over and over again.

Cookbook should show 2 cases:
- same efficiency difference for all items -> use resource.efficiciency and aggregate resource
- different efficiency for different items -> use different operations

**Comment by hichamlahlou** [comment]
tried some javascript to hide the maths but couldn't make it work with frepple_website theme.
So finally I just put the maths at the end, fill free to erase them if you think it's too much details.

**Comment by jdetaeye** [comment]
Edited, and I did indeed remove the last part of details.

I think we should think of the audience we target with the cookbook.
- I have the "RFI-audience" in mind. Ie "does frepple have this functionality -> oh yes.... that's clear "
- You write more with a "detailed functional tester" in mind. Ie someone who wants to understand exactly how a calculation is done.

IMHO it's still okay if we just show the functional tester where to look for the specific output that is of interest in the cookbook.   100% clarification of the calculations isn't needed.
