### ISSUE TITLE
Minor: translation missing for bucket generation command

### ISSUE THREAD

**Issue by jdetaeye** [frePPLe/frepple#315]
![image](https://user-images.githubusercontent.com/5219207/49513987-f12d6d80-f892-11e8-9d10-eb0763b3fbff.png)

**Comment by jdetaeye** [comment]
![image](https://user-images.githubusercontent.com/5219207/49514203-b0822400-f893-11e8-9f88-6907465bd534.png)

**Comment by MichaelNasonov** [comment]
additionally there is no line in the file for translation: 
Sales/Delyvery Orders
![2018-12-05_234317](https://user-images.githubusercontent.com/45640228/49543045-3465fb80-f8e8-11e8-8aae-230a0aff1571.png)

**Comment by MichaelNasonov** [comment]
also Calendars:
![2018-12-05_234349](https://user-images.githubusercontent.com/45640228/49543205-9f173700-f8e8-11e8-9f4f-93e1f0b78ad6.png)

**Comment by MichaelNasonov** [comment]
also dates:
![2018-12-05_233859](https://user-images.githubusercontent.com/45640228/49543239-b8b87e80-f8e8-11e8-9f06-4573c2e67bc1.png)

**Comment by MichaelNasonov** [comment]
and scenario management (in use, free):
![img1370](https://user-images.githubusercontent.com/45640228/49543614-bacf0d00-f8e9-11e8-914a-3abe55e83e94.jpg)

![2018-12-05_235725](https://user-images.githubusercontent.com/45640228/49543626-c15d8480-f8e9-11e8-94a9-af4e0d524e83.png)

**Comment by MichaelNasonov** [comment]
Network Status:
![2018-12-06_000503](https://user-images.githubusercontent.com/45640228/49543984-ba834180-f8ea-11e8-8cb4-e2ee29e3e01b.png)

![2018-12-06_000530](https://user-images.githubusercontent.com/45640228/49544009-c8d15d80-f8ea-11e8-83e0-3e01c4449e09.png)

missing in interface:
![2018-12-06_000801](https://user-images.githubusercontent.com/45640228/49544103-059d5480-f8eb-11e8-8ac0-17820ee22a73.png)

**Comment by jdetaeye** [comment]
Michael,

Your latest translation file was committed and will be deployed on the cloud instance early next week.
There are some things not updated:
- bucket generation: what you found in your file is not in sync with the latest version and needs updating. There are a number of other untranslated strings in the latest version of https://github.com/frePPLe/frepple/blob/master/freppledb/locale/ru/LC_MESSAGES/django.po 
- https://github.com/frePPLe/frepple/blob/master/freppledb/common/static/common/po/ru.po is an additional translation file.  I copied some duplicates from the other file already.

I'll close this ticket for now. Feel free to reopen it, or create another one if you have more remarks on the translations.
