### ISSUE TITLE
Ability to "promote" a scenario to production

### ISSUE THREAD

**Issue by jdetaeye** [frePPLe/frepple#316]

**Comment by jdetaeye** [comment]
This is as identical to the scenario_copy.

The default schema is special is a copy of ways, making this a bit less trivial than it looks:
- scenario table in the main db is leading.  Scenarios only have a old snapshot of the up-to-date content
- user.active has a slightly different meaning: in the main db it means 'this user can log in', and in the scenario it means 'user has access to this scenario'
- user permissions could be different or have changed

First thoughts: pg_dump allows to exclude some tables from the export: "--exclude-table".  That should do the trick I think.

**Comment by hichamlahlou** [comment]
After a night sleep over it, I was actually thinking to restrict the scenario management only to the production instance and hide it in the scenarios.
Reason is that it's more than confusing that, from any scenario, I can trigger a scenario copy for two other scenarios and no task is displayed in my execute log.
For example, I am in scenario 1 and I can copy scenario 2 into scenario 3. I have no clue whether that went well or not (and I need to refresh my screen with F5 to see scenario 3 in the drop down) as I have no task for it on scenario 1, task is on source scenario, scenario 2 in this example.
If we restrict the scenario management to production, I think it's cleaner and we can trigger all the tasks from the production database, they will be seen in the execute log and it's going to be centralized and to me this is clearer. I would keep also the piece of code that writes in the source/destination scenarios "copied from/to scenarioX"
Ideally, I would also like that a scenario release is displayed in the execute log as a task.
@jdetaeye what's your take on this ?

**Comment by jdetaeye** [comment]
>After a night sleep over it, I was actually thinking to restrict the scenario management only to the production instance and hide it in the scenarios.

Won't work nicely for SAIC.   They use scenarios to seperate contracts/business units.  A typical user will have access to only a subset of the scenarios.   The production scenario is an empty one, used only to control who can log in.
With this proposal a user is forced to leave his natural/normal scenario and switch to the production one to trigger a copy.

>Reason is that it's more than confusing that, from any scenario, I can trigger a scenario copy for two other scenarios and no task is displayed in my execute log.

There is a task - created and executed in the source scenario database.  It's the runworker process in the source database that executes the task.  
Benefits:
- If the copy is run from main scenario, you can trigger a copy while the source scenario is in the middle of a task. 
- access rights:   only a user that has access rights to the source database and has scenario-copy rights in it should be able to run the task.

Here's an alternative proposal that will keep these benefits and avoid the confusion you mention:  keep copy as-is but no longer allow to select the source.  the source is always the current database.  In other words, the UI no longer shows "copy from A to B" but only "copy current to B" or "copy into B".

>>Ideally, I would also like that a scenario release is displayed in the execute log as a task.

yes, that's a "historic legacy" / "fossil" that isn't clean.

Also an update of the description isn't run as a task, but immediately run in the view.  

I'm not sure to what extent we revamp the scenario copy.  Apart from the "promote to production" we haven't heard any shortcomings or negative feedback on the scenario management.  From an end user point of view, we are entering low-added-value domain that we better keep in the backlog.
