### ISSUE TITLE
Server Error (500) There's been an error. It's been reported to the site administrators via email and should be fixed shortly. Thanks for your patience.

### ISSUE THREAD

**Issue by libz01** [frePPLe/frepple#334]
I have run the frepplectl.py and see the frepple login website. But after entering the username and password, click on log in to report the error.
Server Error (500) There's been an error. It's been reported to the site administrators via email and should be fixed shortly. Thanks for your patience.
I use frepple5.1.0 and the code also.
And the readme.md is a bit simple, can you make it more detailed?Thanks!

**Comment by jdetaeye** [comment]
The preferred way for addressing configuration or installation issues is the frepple-users mailing list:  https://groups.google.com/forum/#!forum/frepple-users
A github issue is intended to report&track bugs and enhancements requests.

On your issue: if you start your server with the command "frepplectl.py runwebserver" and open the login page then, you will see a more detailed description of the error.  Without that message we don't really know what causes your error.
