### ISSUE TITLE
how to close a table page? 

### ISSUE THREAD

**Issue by flysky9981** [frePPLe/frepple#336]
I find that I can not close the table page that is useless or outdated

**Comment by jdetaeye** [comment]
I don't understand your comment.

**Comment by flysky9981** [comment]
I mean how to close a menu sub page such as the Orders and Demand page .Now I can edit the information on it but can not close it.

**Comment by jdetaeye** [comment]
Please post a screenshot - a picture says more than 1000 words.  I still don't get what you mean.

**Comment by flysky9981** [comment]
sorry, I mean how to close a sub page like this when I finished editing it.
![2019-09-05_215816](https://user-images.githubusercontent.com/18586079/64349073-d73ed800-d028-11e9-9259-7128a988cd67.png)

**Comment by jdetaeye** [comment]
This is a breadcrumb-trail that show the reports that you have recently visited: see https://en.wikipedia.org/wiki/Breadcrumb_(navigation)     It is a very handy feature to quickly step back to a previous screen.

The breadcrumbs are automatically managed by the application. A user doesn't need to take any specific action on them. Just use them as a convenience to step back to a previous screen.
