### ISSUE TITLE
difference between operation and child suboperation in operation definition table

### ISSUE THREAD

**Issue by flysky9981** [frePPLe/frepple#337]
in version 6.0, what's the difference between operations and child suboperations in operation definition table? is child subopeartions deprecated? and if I add an operation in operation definition table using the same name of an existing operation, it would fail. Is this means that I can only create a new operation in the operation definition table rather than reuse an existing one?

**Comment by jdetaeye** [comment]
This type of question should be posted to the user-group.  It's not an issue, bug or enhancement request for which you file a github ticket.  

>>in version 6.0, what's the difference between operations and child suboperations in operation definition table? is child subopeartions deprecated? 

The documentation is very clear on that indeed. See https://frepple.com/docs/current/user-guide/model-reference/suboperations.html

>>and if I add an operation in operation definition table using the same name of an existing operation, it would fail. 

The name is the primary key indeed.

>>Is this means that I can only create a new operation in the operation definition table rather than reuse an existing one?

Correct, reusing operations is no longer possible. In practice I haven't seen any implementation project that did reuse operations.
