### ISSUE TITLE
Dockerfile: the HOST will not be changed!

### ISSUE THREAD

**Issue by yantanglife** [frePPLe/frepple#339]
VOLUME part in dockerfile:
```
VOLUME ["/var/log/frepple", "/etc/frepple", "/var/log/apache2", "/etc/apache2"]
RUN sed -i 's/"HOST": ""/"HOST": "frepple-postgres"/g' /etc/frepple/djangosettings.py
```
This makes djangosetting.py unmodified.

[Note](https://docs.docker.com/engine/reference/builder/#volume):If any build steps change the data within the volume after it has been declared, those changes will be discarded. 

So the two instructions need to be exchanged in order.

**Comment by jdetaeye** [comment]
Good catch...   Will commit a fix shortly
