### ISSUE TITLE
installation problem in ver 6.x

### ISSUE THREAD

**Issue by donukzeka** [frePPLe/frepple#340]
When I try to install 6.0 or 6.1 on Windows 7 Turkish, I get below error and not works. There is no problem with vers 5.x

> Initializing the PostgreSQL database
Create folder: C:\ProgramData\frePPLe\6.1.0\database
Bu veritaban² sistemine ait olan dosyalar²n sahibi "emir" kullan²c²s² olacakt²r.
Bu kullan²c² ayn² zamanda sunucu s³recinin de sahibi olmal²d²r.

> Veritaban² k³mesi "Turkish_Turkey.1254" yerel ayarlar² ile olu¦turulacak.
ͮtan²ml² metin arama yap²land²rmas² "turkish" olarak ayarlanacak.

> Veri sayfas² (data page) do­rulama devre d²¦² b²rak²lm²¦t²r.

> mevcut C:/ProgramData/frePPLe/6.1.0/database dizininin izinleri d³zeltiliyor ... tamam
alt dizinler olu¦turuluyor ... tamam
÷n tan²ml² max_connections se_iliyor ... 100
÷ntan²ml² shared_buffers de­eri se_iliyor ... 128MB
selecting default timezone ... Europe/Moscow
dinamik payla¦²lan bellek (shared memory) uygulamas² se_imi ... windows
yap²land²rma dosyalar² yarat²l²yor ... tamam
÷ny³kleme komut dosyas² _al²¦t²r²l²yor ...tamam
÷ny³kleme sonras² ba¦latmay² ger_ekle¦tirme ...tamam
veriyi diske senkronize etme ...tamam

> ¦¦lem ba¦ar²l². Veritaban² sunucusunu a¦a­²daki gibi ba¦latabilirsiniz:

>    ^"C^:^/Program^ Files^/frePPLe^ 6^.1^.0^/pgsql^/bin^/pg^_ctl^" -D ^"C^:^\ProgramData^\frePPLe^\6^.1^.0^\database^" -l logfile start

> Copy to C:\ProgramData\frePPLe\6.1.0\database
Delete file: C:\Program Files\frePPLe 6.1.0\pgsql\pg_hba.conf
Delete file: C:\Program Files\frePPLe 6.1.0\pgsql\pg_ident.conf
Delete file: C:\Program Files\frePPLe 6.1.0\pgsql\postgresql.conf
sunucunun ba¦lamas² bekleniyor.... tamam
sunucu ba¦lat²ld²

> Creating database schema
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\develop\python36\lib\threading.py", line 916, in _bootstrap_inner
  File "C:\develop\python36\lib\threading.py", line 864, in run
  File "C:\develop\python36\lib\subprocess.py", line 1063, in _readerthread
  File "C:\develop\python36\lib\encodings\cp1254.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 16: character maps to <undefined>

> Traceback (most recent call last):
  File "C:\develop\python36\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
  File "C:\develop\python36\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
  File "frepplectl.py", line 108, in <module>
  File "frepplectl.py", line 43, in main
  File "C:\Program Files\frePPLe 6.1.0\bin\custom\django\__init__.py", line 5, in <module>
    __version__ = get_version(VERSION)
  File "C:\Program Files\frePPLe 6.1.0\bin\custom\django\utils\version.py", line 31, in get_version
    git_changeset = get_git_changeset()
  File "C:\Program Files\frePPLe 6.1.0\bin\custom\django\utils\version.py", line 85, in get_git_changeset
    timestamp = git_log.communicate()[0]
  File "C:\develop\python36\lib\subprocess.py", line 843, in communicate
  File "C:\develop\python36\lib\subprocess.py", line 1115, in _communicate
IndexError: list index out of range
x 1 x
ERROR CREATING DATABASE SCHEMA!!!
 
> Review the file 'bin\\custom\\djangosettings.py' and run 'frepplectl migrate'
 
> Created uninstaller: C:\Program Files\frePPLe 6.1.0\uninst.exe
Completed

**Comment by jdetaeye** [comment]
Can you try whether editing the file C:\Program Files\frePPLe 6.1.0\bin\custom\django_init_.py fixes the problem?
The line with:
   VERSION = (2, 2, 8, 'alpha', 0)
should be changed to:
  VERSION = (2, 2, 8, 'final', 0)

**Comment by donukzeka** [comment]
There is only djangosettings.py and djangosettings.py.old files in described path. 

I searched for that phrase and found below one only
C:\Program Files\frePPLe 6.1.0\bin\custom\dateutil\_version.py  -> Line 4: version = '2.8.0'

When I change windows 7 language to english it installs but again gives some errors.

**Comment by jdetaeye** [comment]
> ... windows 7 ...

https://support.microsoft.com/en-us/help/4057281/windows-7-support-will-end-on-january-14-2020
You have 3 days left of support from Microsoft :-)

Can you try with the latest beta-installer of the upcoming 6.2 release?  It's available here: 
https://github.com/frePPLe/frepple/releases/download/6.2.0/frePPLe_6.2.0_setup.exe
https://github.com/frePPLe/frepple/releases

Try installing in English and in path that only has ascii characters. 
If that doesn't work, you'll need to be more specific about "... gives some errors".

**Comment by jdetaeye** [comment]
closing old inactive issue

**Comment by donukzeka** [comment]
problem was about apache, I have uninstalled xampp and problem solved.
