### ISSUE TITLE
permission denied to create role

### ISSUE THREAD

**Issue by overthrowrobotics** [frePPLe/frepple#359]
I'm attempting to install frePPLe on Ubuntu 18.04 alongside Odoo 13. Odoo is on port 8069 and nginx is acting as a proxy on port 80. 

odoo@odoo:/var/log/odoo$ sudo frepplectl migrate --noinput
Operations to perform:
  Apply all migrations: admin, archive, auth, common, contenttypes, execute, input, metrics, odoo, output, reportmanager
Running migrations:
  Applying common.0017_sql_role...Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.InsufficientPrivilege: permission denied to create role

...
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: permission denied to create role

My pg_hba.conf file: 

local   all             all                                     trust
host    all             all             127.0.0.1/32            md5
host    all             all             ::1/128                 md5
local   replication     all                                     peer
host    replication     all             127.0.0.1/32            md5
host    replication     all             ::1/128                 md5

In postgresql I created a user called frepple with password frepple and have that in the djangosettings.py file. 

I've tried every combination of settings in pg_hba.conf I can and djangosettings.py. Following the install script per line does not seem to work with Odoo and after 3 hrs on this I'm hoping to get some advice on what to do. Would like to try community edition before considering enterprise.

**Comment by overthrowrobotics** [comment]
I ended up installing on a fresh Ubuntu 18 without Odoo and was able to get it working. Running into problems with the Odoo connector, I made a ticket under that rep.

**Comment by jdetaeye** [comment]
- This message belongs on the user forum, not as an issue here.  A simple "alter user USR createrole" fixes that.
- Your database user was missing the "createrole" permission.
