### ISSUE TITLE
psycopg2.DataError: extra data after last expected column

### ISSUE THREAD

**Issue by max3903** [frePPLe/frepple#364]
# Environment

* FrePPLe 6 in Docker with Ubuntu 18.04 and Odoo connector.
* Odoo 12 with the FrePPLe connector

# Steps to reproduce

* Admin > Execute
* In "Create a plan", select all the options except "Write results to Odoo"
* Click on Launch
* Wait for the task to complete

# Result

The task failed with this error message in the log

```
INFO Start step 171 'Export forecast metrics' at 23:53:04
Error during planning: extra data after last expected column
CONTEXT:  COPY forecast_tmp, line 949: "[K600-0106] "Silver" on Black Strymon T-Shirt XL..."

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/freppledb/common/commands.py", line 541, in <module>
    register.run(database=database)
  File "/usr/lib/python3/dist-packages/freppledb/common/commands.py", line 481, in run
    cls.reg.run(**cls.arguments)
  File "/usr/lib/python3/dist-packages/freppledb/common/commands.py", line 213, in run
    step.run(**PlanTaskRegistry.getArguments())
  File "/usr/lib/python3/dist-packages/freppledb/forecast/commands.py", line 991, in run
    cursor.copy_from(file=tmp, table="forecast_tmp")
psycopg2.DataError: extra data after last expected column
CONTEXT:  COPY forecast_tmp, line 949: "[K600-0106] "Silver" on Black Strymon T-Shirt XL..."

Error: Error executing Python command
```

# Expected result

Task is successful and plan is exported with products whose name contain quotes and/or double-quotes.

**Comment by jdetaeye** [comment]
Hi Maxime,

Thanks for reporting this problem.  Quotes and tabs caused trouble in that part of the export indeed.
I'll mail you the fix to be applied - which is in the enterprise-part of the code.

**Comment by jdetaeye** [comment]
Issue has been fixed since.
