### ISSUE TITLE
No resource owner in API

### ISSUE THREAD

**Issue by tjheiska** [frePPLe/frepple#368]
`    {
        "name": "Operator",
        "description": null,
        "category": null,
        "subcategory": null,
        "type": "default",
        "maximum": "1.00000000",
        "maximum_calendar": null,
        "location": null,
        "cost": null,
        "maxearly": null,
        "setupmatrix": null,
        "setup": null,
        "efficiency": null,
        "efficiency_calendar": null,
        "constrained": null,
        "source": null,
        "lastmodified": "2021-06-16T14:36:23.060718"
    }` is missing the owner. Also POST does not accept it as field so cannot create human resource pool using REST API.

**Comment by jdetaeye** [comment]
You're right.   The field was missing in the definition of the REST API.

Trivial to fix.
