### ISSUE TITLE
Adding a new entry to an existing calendar results in a 500 error

### ISSUE THREAD

**Issue by steveblamey** [frePPLe/frepple#369]
I have this problem in the community edition. Also reported by other users on the forum, https://groups.google.com/g/frepple-users/c/sjRNoyvvaKk/m/QeMOc2i1AwAJ

**Comment by jdetaeye** [comment]
Confirmed as a bug.

The problem happens at:
https://github.com/frePPLe/frepple/blob/c805462b86df624e7af6d7820cb58b51a738389d/freppledb/common/adminforms.py#L214 
The message argument is more complex than this piece of code can currently handle.
