### ISSUE TITLE
Question: Long operation splitted to working hours

### ISSUE THREAD

**Issue by tjheiska** [frePPLe/frepple#370]
Hi. Is there a clean  way to split the operation to respect working hours? Creating resource with defaults and 7 hour working day and operation with 8 hour duration will never be scheduled in my model.

**Comment by jdetaeye** [comment]
- Please do NOT use a github issue for questions. Issues are for tracking bugs and development work.  The user forum https://groups.google.com/g/frepple-users is the place for questions.

- The answer to your question can be found on https://frepple.org/docs/current/user-guide/examples/calendar/calendar-working-hours.php

**Comment by tjheiska** [comment]
So sorry, won't happen again!
