### ISSUE TITLE
/erp/upload/ 500 (Internal Server Error) when Export to odoo ( Manufacturing orders )

### ISSUE THREAD

**Issue by chenrongxu** [frePPLe/frepple#372]
Message: '%s: %s'
Arguments: ('Internal Server Error', '/erp/upload/')
--- Logging error ---
Traceback (most recent call last):
  File "C:\develop\python38\lib\http\client.py", line 871, in _get_hostport
ValueError: invalid literal for int() with base 10: '8081frepple'

**Comment by jdetaeye** [comment]
Without a stack trace of the internal server error, we can't analyze the problem.

**Comment by chenrongxu** [comment]
> Without a stack trace of the internal server error, we can't analyze the problem.

Message: '%s: %s'
Arguments: ('Internal Server Error', '/erp/upload/')
--- Logging error ---
Traceback (most recent call last):
File "C:\develop\python38\lib\http\client.py", line 871, in _get_hostport
ValueError: invalid literal for int() with base 10: '8081frepple'

**Comment by jdetaeye** [comment]
Looks like the parameter "odoo.url" is not configured correctly.
Good values are:      http://localhost:8081/      https://myserver/
Make sure you have a slash at the end of your parameter value.

**Comment by jdetaeye** [comment]
Closing this one as it's a misconfiguration issue rather a bug that needs fixing.
