### ISSUE TITLE
Enhancement Suggestion - Conditional Supply Paths

### ISSUE THREAD

**Issue by govindsmenokee** [frePPLe/frepple#374]
Hi,
There are some cases where the supply path will change based on the available items. To Explain this properly let us take the case of automotive headlamp manufacturing where BOM contains LEDs that have different bin codes. The bin code will not be known during the time of placing a purchase order. The bin codes are only known post dispatch or on arrival of the LEDs based on which the resistors are matched in series to get the standardised lumens output from the headlight assembly.

Just wanted to know if adding a new feature for these conditional supply paths would benefit the entire community or is there a better way of doing it.

Im adding an attachment just to have a more clear picture on the scenario
<img width="1077" alt="Screenshot 2021-07-08 at 1 31 18 AM" src="https://user-images.githubusercontent.com/2034781/124821423-50dcdf80-df8c-11eb-9d96-e1c28a4c3c35.png">
Here SMT Bin 1, SMT Bin 2 and SMT Bin 3 are alternate operations with the same priority. the problem here is while placing an order for the led it will be for the common led where the bin code is unknown and when we actually have an update on the bin code we will update the purchase order and generate the plan again at that point the system should pick the path with the matching bin code led. for example post shipment if we get to know that LED Bin 1 is shipped we will update the purchase order from LED ---> LED Bin 1 and regenerating the plan should consider that path. The best option would be to add one more search mode where material availability should be considered for picking the alternate supply path.

Hoping for some good thoughts and discussions on this.

Regards,
Govind

**Comment by jdetaeye** [comment]
>>The best option would be to add one more search mode where material availability should be considered for picking the alternate supply path.

You can already do something similar with the "minimum cost" search mode:
- set the cost in the itemsupplier table to 1000
- set the cost in the operation table to 1
- set the search mode to "minimum cost" in the operation table
As a result, any of the supply path that can use stock/confirmed supply and doesn't need to generate extra purchase order will have a much lower cost.
