### ISSUE TITLE
Buffer - maximum

### ISSUE THREAD

**Issue by petrakozielova** [frePPLe/frepple#378]
Hello,
I can't find field maximum on Buffer form. I am not sure, if it is a bug or if this field is not available in some cases.
I also have comments on documentation - there is the following information about maximum "Refers to a calendar storing the maximum inventory level.", although maximum is type of double.

![obrazek](https://user-images.githubusercontent.com/86603226/126636268-4654f276-dad5-48ff-a76d-48dcb608a666.png)

**Comment by jdetaeye** [comment]
The field exists in the planning engine, but it has no functionality attached to it (yet).
For this reason, we are not showing the presence of the field in form.
