### ISSUE TITLE
Resource constraint

### ISSUE THREAD

**Issue by petrakozielova** [frePPLe/frepple#381]
Hello,
I have problem with constraining owner Resource. When the owner is constrained (although its calendar is available all the time) and its members are not constrained, the related demand is not planned. When I uncheck the constrained parameter, demand is planned.
I also tried to assign same calendar (with default value 1) to all resources, all resources constrained and the demand was still not planned. Then I unchecked the resources, which are owners and the demand was still not planned. I am not sure if there is some problem with my calendars or it is a bug.

[planned.xlsx](https://github.com/frePPLe/frepple/files/6867188/planned.xlsx)
[not_planned.xlsx](https://github.com/frePPLe/frepple/files/6867189/not_planned.xlsx)

**Comment by jdetaeye** [comment]
This was a bug indeed.  Good catch.
Thanks for reporting!
