### ISSUE TITLE
I can't log in to Frepple from the odoo frame

### ISSUE THREAD

**Issue by Icon003** [frePPLe/frepple#391]
I will deploy Odoo and Frepple on different machines, set up interaction with them according to the documentation: https://frepple.org/docs/current/integration-guide/odoo-connector.php#installation-and-configuration . Frepple appeared in odoo, but I had to add in djangosetting.py X_FRAME_OPTIONS = "ALLOWALL" because I caught an error related to the prohibition of displaying Frepple in the frame. Frepple displayed the login page in the Odoo frame, but I can't log in, I enter the username and password, and the page is updated and again offers to log in, and so on endlessly.

Please tell me what the problem is, I am grateful in advance.

**Comment by Icon003** [comment]
I realized from the logs that I was getting CSRF token errors

[Tue Aug 17 22:40:49.907843 2021] [wsgi:error] [pid 30:tid 140580563961600] [remote 37.214.48.243:54813] ERROR Invalid user in webtoken
[Tue Aug 17 22:40:55.537201 2021] [wsgi:error] [pid 31:tid 140580563961600] [remote 37.214.48.243:30755] ERROR CSRF failure detected
[Tue Aug 17 22:40:55.537980 2021] [wsgi:error] [pid 31:tid 140580563961600] [remote 37.214.48.243:30755] INFO Forbidden (CSRF cookie not set.): /data/login/

How can I avoid this?

**Comment by jdetaeye** [comment]
Does your odoo user match the user name in frepple? The first line in the error suggests that not the case.
