### ISSUE TITLE
Does your odoo user match the user name in frepple? The first line in the error suggests that not the case.

### ISSUE THREAD

**Issue by Icon003** [frePPLe/frepple#393]
Does your odoo user match the user name in frepple? The first line in the error suggests that not the case.

_Originally posted by @jdetaeye in https://github.com/frePPLe/frepple/issues/391#issuecomment-900829116_

I don't understand what you are talking about, but why would a user match in two different systems? I'm trying to log in to frepple with the standard admin admin under which it goes if I don't use frame

**Comment by Icon003** [comment]
I specially created a user in frepple one - on-one with odoo, I try to log in and get an error with a csfr token.

[Wed Aug 18 06: 34: 25.041670 2021] [wsgi: error] [pid 24:tid 140236854331136] [deleted 37.214.48.243:20758] ERROR CSRF error detected
[Wed Aug 18 06: 34: 25.042667 2021] [wsgi: error] [pid 24:tid 140236854331136] [deleted 37.214.48.243:20758] INFORMATION is prohibited (CSRF cookie is not installed.): / data/login/

**Comment by jdetaeye** [comment]
Closing.   Issues https://github.com/frePPLe/frepple/issues/ are for tracking bugs & enhancements.
Use discussions for general questions, configuration issues, etc 

I converted your previous issue into a discussion https://github.com/frePPLe/frepple/discussions/392
