### ISSUE TITLE
Prefered PO 

### ISSUE THREAD

**Issue by petrakozielova** [frePPLe/frepple#396]
Hello,

I have question about prefering PO over MO. In case the demand is planned late, the Purchase Order is prefered although Item Supplier has higher priority and also duration than Operation. Wouldn't it be more convenient if the record which lasts shorter time was selected so the delay was smaller? I am not sure if it is a bug or expected behaviour.

[frepple(13).xlsx](https://github.com/frePPLe/frepple/files/7044413/frepple.13.xlsx)

**Comment by jdetaeye** [comment]
This is working as expected. The solver is indeed selecting the alternate with the smallest delay.


After setting the parameter "plan.loglevel' to 9, I see the following in the log file:
1. Solver evaluates "Výroba položky X (verze 2)", but that operation can't produce before 2021-08-31T07:10:00.   Indeed, the operation needs to wait for "Purchase B - alt. @ Pobočka Ostrava from Dřevoprodej Svoboda" to arrive before production can start. 
2. Solver evaluates "Výroba položky X (verze 1)", but that operation also can't produce before 2021-08-31T07:10:00. Also here the production can only start after a purchased material comes in.
3. Solver evaluates purchasing the item "Purchase X @ Pobočka Ostrava from ASKO - NÁBYTEK", and giving the lead time the earliest arrival is 2021-08-31T02:00:00
4. After some more steps, the solver will plan the demand using the purchasing operation.

![image](https://user-images.githubusercontent.com/5219207/131491116-bfd4ac83-c05d-44e6-9902-91e69e845463.png)
