### ISSUE TITLE
Repeated child bug

### ISSUE THREAD

**Issue by MJD093** [frePPLe/frepple#41]
When attempting to pull BoMs (Bill of Material) into frePPLe via the "Create a Plan" command, the operation will fail due to the parts involved in the BoM not being unique. 

That is to say, sometimes the same part will be used in a BoM twice, once to build a child part which is then used to make the parent product, and once again used in the construction of the parent product itself.

  A + B =>C
  A + C =>D

If in D's BoM, part C has type=phantom then the MO (mrp_production model) will require A + B (the children of C) and A again (directly).
So the MO will have 3 lines but product A will appear on 2 lines.

---

![log file error 2](https://cloud.githubusercontent.com/assets/8591581/4108215/ca77e646-31d3-11e4-9dd3-8b2c2c5b4e38.PNG)
(Log file entry)

---

https://www.dropbox.com/sh/rlneb3b2d56vks2/AAAv0oyc7_cCkVz7YRGLybZea?dl=0
(Dropbox file of the above image)

**Comment by jdetaeye** [comment]
Closing old ticket
