### ISSUE TITLE
Phantom BoM from Odoo/OpenERP

### ISSUE THREAD

**Issue by MJD093** [frePPLe/frepple#42]
When pulling in BoM (Bill of Material) data from OpenERP, frePPLe will encounter an error that will break the operation of the "Create a Plan" command. 

Namely that the BoMs in question have repeating parts consumed within the manufacture of the parent part.

It's possible to have the same product more than once in a mrp_production when using phantom BOMs:

  A + B =>C
  A + C =>D

If in D's BOM part C has type=phantom then the MO (mrp_production model) will require A + B (the children of C) and A again (directly).
So the MO will have 3 lines but product A will appear on 2 lines.

That's a valid business case (there are bugs around phantom BOMs on Odoo which have been raised) - FrePPLe needs to handle these too, especially if it's generating MO (mrp_production) instances directly.

---

![log file error 2](https://cloud.githubusercontent.com/assets/8591581/4108671/cfcf9a6a-31da-11e4-92cd-70f0a0e72171.PNG)
(Log file)

---

https://www.dropbox.com/sh/rlneb3b2d56vks2/AAAv0oyc7_cCkVz7YRGLybZea?dl=0
(Dropbox file of the above image)

**Comment by jdetaeye** [comment]
Closing old tickets
