### ISSUE TITLE
time switches from 24hours system to 12 hour system after dragging and dropping a manufacturing order

### ISSUE THREAD

**Issue by snelstim** [frePPLe/frepple#420]
Hello,

when I drag and drop a manufacturing order in the calendar display view the time is switching to 12hours system instead of 24 hour system. When I select 16:00 it shows up at 04:00.
when I open the time selection box again it shows as 04:00 so it seems it only allows the plan in the morning.
Anyone else has this issue?
I'm using frepple 6.17.1

**Comment by jdetaeye** [comment]
Looks a bug indeed...

**Comment by jdetaeye** [comment]
Fixed in https://github.com/frePPLe/frepple/commit/7253eca156f74c145918baca7898eddccb333558 
Thanks for reporting the issue!
