### ISSUE TITLE
Problem with Operation.BatchingWindow

### ISSUE THREAD

**Issue by petrakozielova** [frePPLe/frepple#445]
Hello, I have problem when using operation batch window. 
When I do not use it,the demand is planned, but when I use it there is problem. There is request for black chair on 17.1. and also on 31.1. Only demand with due 31.1 is planned. I do not see why demand with due 17.1. was not planned. There is a lot of time to manufacture black chair from both demands to earlier date. 

[frepple(4).xlsx](https://github.com/frePPLe/frepple/files/7779346/frepple.4.xlsx)

**Comment by jdetaeye** [comment]
On the Community Edition, setup matrix optimization isn't available and the issue is irrelevant.
If the issue is with the Enterprise Edition, please don't report it here.
