### ISSUE TITLE
Problem with SetupRule.Resource

### ISSUE THREAD

**Issue by petrakozielova** [frePPLe/frepple#446]
Hello,
I have problem with Resources used for setup matrix rules. There is a resource Technician who configurates resource painting line through its setup matrix rules. It is infinite and unconstrained and has same calendar as painting line. Yet,the demands are not planned when resource Technician is used. When I delete it from setup rules, the demands are planned,so the problem is Technician.
From log file I couldn't find information about the problem. There is just information that operation replenished items, but for some reason buffer answers 0.
_Alternate operation 'Replenish Light blue chair @ Factory' answers: 2
          Buffer 'Light blue chair @ Factory' answers: 0  2030-12-31T00:00:00_

[frepple(5).xlsx](https://github.com/frePPLe/frepple/files/7779466/frepple.5.xlsx)

**Comment by jdetaeye** [comment]
On the Community Edition, setup matrix optimization isn't available and the issue is irrelevant.
If the issue is with the Enterprise Edition, please don't report it here.

**Comment by petrakozielova** [comment]
Thank you for repply.
