### ISSUE TITLE
Frepple install disables other configured web sites on same server

### ISSUE THREAD

**Issue by timo12357** [frePPLe/frePPLe#50]
Lubuntu 12.04
Frepple 2.3 locally compiled
SugarCRM 6.5.2

Installing Frepple blocks or destroys access to existing SugarCRM installation using same Apache server. Installing SugarCRM after Frepple does not help. http://localhost/crm is redirected to http://localhost/admin i.e. the Frepple login page.

**Comment by jdetaeye** [comment]
Different deployments will have different requirements for deployment: port number, SSL, authentication, load balancing, nginxc-vs-apache, etc
In such a context a one-size-fits-all configuration for the web server doesn't exist. 

The one provided by frePPLe should be seen as a starting point - a system administrator can easily update it to their needs.

Closing this issue.
