### ISSUE TITLE
Documentation update: link to ERPNext integration

### ISSUE THREAD

**Issue by jdetaeye** [frePPLe/frepple#502]
### Discussed in https://github.com/frePPLe/frepple/discussions/501

<div type='discussions-op-text'>

<sup>Originally posted by **Drayang** February 18, 2022</sup>
Recently i was working on a ERP system called ERPNext and was trying to  integrate Frepple with ERPNext in order to utilise the Frepple as the production scheduling tool. I successfully developed a custom app (i.e a common concept in ERPNext to add on feature without changing the original source code) that act as a connector to transfer data between frepple and ERPNext. The idea is by using the REST API to have a bidirectional data transfer. Besides, I used the data mapping for Odoo connector as the reference and end up having a pretty similar data mapping for ERPNext and Frepple. Here is the github link for the app i have created: [msf4-0/ERPnext- Frepple-Integration](https://github.com/msf4-0/ERPNext-Frepple-Integration.git) and I wonder whether you are interested to see it as one of the potential connector or feature that can be added to the Frepple Production Scheduling software?

Thank you!</div>

-> Update documentation with links to this github repository.

**Comment by mike-ivc-inform** [comment]
Each new software that is added to the list for integration helps frepple APS become a universal planner tool.

**Comment by jdetaeye** [comment]
Added link to https://github.com/msf4-0/ERPNext-Frepple-Integration.git in the frepple documentation.
