### ISSUE TITLE
Deleting operationplan deletes demand entries.

### ISSUE THREAD

**Issue by timo12357** [frePPLe/frePPLe#51]
Lubuntu 12.04
Frepple 2.3

Deleting an operationplan warns that it will delete also demand entries. It indeed does. This may or may not be a feature, but deleting the operation plan should imho leave the demand intact.

Timo

**Comment by jdetaeye** [comment]
How are you deleting these? I don't think there is a screen where you can delete an individual operationplan from the generated output.

**Comment by timo12357** [comment]
Input -> Operationplans -> Tick the tick box of an operation -> Click the minus sign "-" in the upper right corner.

**Comment by jdetaeye** [comment]
Input -> operationplans doesn't have a field that is referring to a demand at all.
It's simply not possible that a demand gets deleted from that screen.

(There is an output operationplan table as well, which does have a demand field. But that one is completely separate from the "input->operationplan")
