### ISSUE TITLE
possible variable typo in freppledb/output/commands.py

### ISSUE THREAD

**Issue by maxware0715** [frePPLe/frepple#510]
https://github.com/frePPLe/frepple/blob/6d5e85e9ef55a2df5a8956050793f37fea1e0a65/freppledb/common/commands.py#L406
if isinstance(existing, PlanTaskParallel):
                # Already existing as parallel group
           -> s.addTask(task)

Should s means existing?

**Comment by jdetaeye** [comment]
Doesn't make a difference.  From the lines just before, it's clear that "existing == s" in that line.
