### ISSUE TITLE
docker container, djangosetting.py unmodified

### ISSUE THREAD

**Issue by ZOOUQinn** [frePPLe/frepple#520]
According docker-container.rst [document](https://github.com/frePPLe/frepple/blob/master/doc/installation-guide/docker-container.rst#deployment-with-custom-extension-apps), here is my dockerfile for building customized image:

```
FROM ghcr.io/frepple/frepple-community:latest
RUN echo "MYAPPSETTING=True" >> /etc/frepple/djangosettings.py
```

However, the setting didn't append to djangosettings.py configuration file.

Would you please check it?

**Comment by jdetaeye** [comment]
Apart from a trivial typo which you already corrected in your example dockerfile (https://github.com/frePPLe/frepple/commit/79ba8393c3e5df130cf8b37d61d0edbbea3471df) this works as expected in my test.
