### ISSUE TITLE
Task status reports "Failed with exit code 127"

### ISSUE THREAD

**Issue by andrejk10** [frePPLe/frepple#525]
Message: Failed with exit code 127  
Arguments: --constraint=8 --plantype=2 --env=supply

This happend after initial installation and creation of first purchase order.

regards,
andre
![Capture](https://user-images.githubusercontent.com/61164971/166303006-8bafcb75-7cee-4751-ae8d-ecbd6f7ff37a.JPG)
j

**Comment by jdetaeye** [comment]
Looks like the frepple executable isn't found for some reason.

Closing this issue:  For installation or configuration problems, please post to the discussion group https://github.com/frePPLe/frepple/discussions       File an issue if you report a bug or enhancement request.
