### ISSUE TITLE
Resource report display graph has +1 day offset to calendar bucket

### ISSUE THREAD

**Issue by timo12357** [frePPLe/frePPLe#54]
Calendar bucket set to Monday to Friday = 1, Saturday and Sunday = 0
Resource report display graph shows Sunday to Thursday =1 Friday and Saturday = 0

**Comment by jdetaeye** [comment]
Works for me with the demo dataset.

This issue doesn't provide any way to reproduce or analyze the issue in more detail. Hence, throwing it in the dustbin...
