### ISSUE TITLE
Cockpit randomly fails to load completely

### ISSUE THREAD

**Issue by timo12357** [frePPLe/frePPLe#55]
Most of the times the Cockpit fails to load part of the widgets and loads a second copy of itself into the widget window. This happens both when using frePPLe in the LAN and internet.

My uneducated guess is that there is some kind of timeout happening.

Timo

**Comment by jdetaeye** [comment]
I've seen this on a rare occasion as well, but have not been able to reproduce.  If somebody can debug this a bit deeper, that'ld be a great help to resolve this.

**Comment by timo12357** [comment]
It happens here almost every time. Is there a debug command I can use to start frePPLe with? I could try to at least log something.

**Comment by jdetaeye** [comment]
Best way is to use the google chrome browser, and hit F12 to open the developer tools.

I'ld need:
* A screenshot of such a problem load.
* A screenshot of the "network" tab of such problematic refresh.

**Comment by timo12357** [comment]
![kuvakaappaus 2015-05-06 20 58 18](https://cloud.githubusercontent.com/assets/11517762/7499855/b4a92164-f432-11e4-9d89-9cb8d9382df6.png)
![kuvakaappaus 2015-05-06 20 59 04](https://cloud.githubusercontent.com/assets/11517762/7499867/c80ea0e4-f432-11e4-9040-cb2fdb06d659.png)
![kuvakaappaus 2015-05-06 20 59 50](https://cloud.githubusercontent.com/assets/11517762/7499886/e28ad12c-f432-11e4-931c-1efec8dc3ccb.png)

**Comment by timo12357** [comment]
![screenshot 1](https://cloud.githubusercontent.com/assets/11517762/7500322/9fb04852-f435-11e4-9e1b-cd95b4526362.png)
![screenshot 2](https://cloud.githubusercontent.com/assets/11517762/7500323/a0200cf0-f435-11e4-9385-2faa9bce619f.png)
![screenshot 3](https://cloud.githubusercontent.com/assets/11517762/7500324/a03d3096-f435-11e4-9438-f79b3ab958a6.png)

**Comment by jdetaeye** [comment]
bug fixed with commit 5537242d975f4017b103ca21b177e769aaccc115

**Comment by timo12357** [comment]
Great news! Good that you found the bug.

Timo
