### ISSUE TITLE
Getting the ModuleNotFoundError: No module named 'freppledb.myapp'

### ISSUE THREAD

**Issue by MaxbyteTechnologies** [frePPLe/frepple#551]
### Discussed in https://github.com/frePPLe/frepple/discussions/550

<div type='discussions-op-text'>

<sup>Originally posted by **MaxbyteTechnologies** September  4, 2022</sup>
Getting the ModuleNotFoundError: No module named 'freppledb.myapp' when trying to execute the command 'frepplectl migrate' and 'frepplectl makemigrations my_app'

Following the steps from 'Creating an extension app' from Developer Guide'</div>

**Comment by jdetaeye** [comment]
Please learn Python.  Just make sure you place your python module somewhere in your python path.

It's NOT DONE to create an issue if you don't get a reply to your discussion.
