### ISSUE TITLE
JS Crash on Display Calendar (manufacturing order)

### ISSUE THREAD

**Issue by zipus** [frePPLe/frepple#576]
In manufacturing order, in the display calendar, when try to move drag and dropping to a different date the card moves to the correct date with unsaved tag.
But when trying to save the changes, it crashes in js console without saving:
`frepple-operationplandetail.js:1759:8`
```
Uncaught TypeError: e.deleted is undefined
    getDirtyCards frepple-operationplandetail.js:1759
    getDirtyData (index):591
    save frepple.js:268
    onclick
```
Tested on 6.24 and 6.25

**Comment by jdetaeye** [comment]
Could reproduce indeed.
The issue was already corrected on the master branch in the meantime.
