### ISSUE TITLE
Missing minor releases

### ISSUE THREAD

**Issue by zipus** [frePPLe/frepple#597]
Why there are [releases (8.0.3, 8.0.2, 8.0.1)](https://frepple.com/docs/current/release-notes.php#id1) if those are [not tagged](https://github.com/frePPLe/frepple/tags)?

**Comment by jdetaeye** [comment]
Closing.

**Comment by zipus** [comment]
For anyone with the same question, seams that the criteria changed, don't know why, but now there are minor versions tagged also and available as docker images.

**Comment by jdetaeye** [comment]
The criteria & policies have NOT changed.

There were some critical issues with the 8.1.0 Community Edition, making it almost unusable. So, we *exceptionally* created a patch release.

Why this policy?
Our open source community is unfortunately quite passive and not actively contributing a lot in the development.   For the 8.2 release (tagged later today) we have 79 commits from the frepple team and 1 contribution: https://github.com/frePPLe/frepple/compare/8.1.0...master 
That's hardly a win-win situation, isn't it?  Why would we care spending the extra work of creating patch releases for this community?   It's the enterprise and cloud editions that keep frepple alive.

**Comment by zipus** [comment]
My first concern on creating the issue was that in specific. What if a new version becomes not usable? I'll be stuck with a not usable software until next version.
So I want to know more about the "exceptionally" rules. Which are they? When can I expect new patches (exceptionally)?


Is there any problem in automating the releases? I don't know too much about the CICD specifics of Frepple project but normally all CI/CD mechanisms are capable of making a new release patch, publish it and tag them. So for me the extra work it's a matter of Github actions configs. Or am I missing something that works different on frepple?

**Comment by jdetaeye** [comment]
>My first concern on creating the issue was that in specific. What if a new version becomes not usable? I'll be stuck with a not usable software until next version.

Right, You stay on the latest stable release.

> So I want to know more about the "exceptionally" rules. Which are they? When can I expect new patches (exceptionally)?

The exceptions are entirely at the discretion of the frepple team. As user of the Community Edition, it's simple: don't expect any patch releases.

> Is there any problem in automating the releases? I don't know too much about the CICD specifics of Frepple project but normally all CI/CD mechanisms are capable of making a new release patch, publish it and tag them. So for me the extra work it's a matter of Github actions configs. Or am I missing something that works different on frepple?

Technically, the release creation is already automated with github actions.

Conceptually, the Community Edition only has "community support" and no "enterprise-grade support".
See https://frepple.com/blog/community-edition-vs-enterprise-edition/ on the distinction.
