### ISSUE TITLE
Error @ /detail/auth/group/1/ @ frePPLe V3

### ISSUE THREAD

**Issue by ElevimRG** [frePPLe/frePPLe#60]
[Thu Jan 07 21:45:09.148242 2016] [wsgi:error] [pid 13834] ERROR Internal Server Error: /detail/auth/group/1/
[Thu Jan 07 21:45:09.148358 2016] [wsgi:error] [pid 13834] django.core.urlresolvers.NoReverseMatch: Reverse for 'common_group_change' with arguments '('dummy',)' and keyword arguments '{}' not found. 0 pattern(s) tried: []

**Comment by jdetaeye** [comment]
Fixed now.
Thanks for reporting the problem!
