### ISSUE TITLE
frePPLe V3 @ Cockpit - Save Widgets

### ISSUE THREAD

**Issue by ElevimRG** [frePPLe/frePPLe#61]
Hey there,

So far I can see - the settings of the widgets are not saved yet.
I can delete some of them (or reorder), but it won´t get save when I reenter the Cockpit.

Is this intended?

**Comment by jdetaeye** [comment]
The setting is saved... in the Enterprise Edition of frePPLe.  Try it out on the demo environment at https://demo.frepple.com

The functionality is not available in the Community Edition.
