### ISSUE TITLE
Terms/sentences meanings for helping translation

### ISSUE THREAD

**Issue by sbadux** [frePPLe/frepple#613]
Hello,
can you please brifly explain what the following terms/sentences mean so I can improve the translation?

1. Successor part (New Item -> Advanced)

2. "Release: You will lose ALL data in this scenario!". I would like to know where it's used, I can't fully understand the meaning of 
the "Release:" at the beginning of the sentence

3. "Promote: All data will be copied to Production". I would like to know where it's used, I can't fully understand the meaning of the "Promote:" at the beginning of the sentence

4. "Measure". I can't understand what do you refer with the term "measure". 

5. Using the term "adjustment" on the orders (eg. orders adjustment) you mean when there is an error and the order must be rectified?

6. What do you mean with "setup duration override"

**Comment by jdetaeye** [comment]
> 1. Successor part (New Item -> Advanced)

Only in enterprise edition. Used when you would have different versions of an item. The inventory planning screen then shows an aggregate view across all versions.

> 2. "Release: You will lose ALL data in this scenario!". I would like to know where it's used, I can't fully understand the meaning of  the "Release:" at the beginning of the sentence

![image](https://github.com/frePPLe/frepple/assets/5219207/e6e97a0e-2ee7-4508-a403-f0985f8eca94)

> 3. "Promote: All data will be copied to Production". I would like to know where it's used, I can't fully understand the meaning of the "Promote:" at the beginning of the sentence

See above.

> 4. "Measure". I can't understand what do you refer with the term "measure". 

Used in the forecasting module.  You can define extra data rows which we store in the database and show in the user interface.   These are called "measures".  

![image](https://github.com/frePPLe/frepple/assets/5219207/aba58fab-40c1-4eb5-bf19-5851504be8cb)

> 5. Using the term "adjustment" on the orders (eg. orders adjustment) you mean when there is an error and the order must be rectified?

Used in the forecasting module.   There are situations where the demand history needs some corrections to adjust for exceptional demands. Without a correction the computed statistical forecast wouldn't be realistic.

> 6. What do you mean with "setup duration override"

Has to do with the setup matrix feature.   We normally compute the changeover time between different resource configurations.  But users have the ability to manually apply a different setup time.

![image](https://github.com/frePPLe/frepple/assets/5219207/15c122c2-6dea-4337-b83c-8b54d2e5b8fb)
