### ISSUE TITLE
New problem type for modeling errors

### ISSUE THREAD

**Issue by jdetaeye** [frePPLe/frePPLe#77]
New problem type to replace the current print:
      Warning: Can't replenish buffer 'X'
Same problem should be raised when the number of supply options is > 100.
Both indicate potential modeling mistakes.

**Comment by jdetaeye** [comment]
New problem report shown under 'admin'.
Shows "invalid data problems" when:
- A buffer has no replenishment method
- A buffer has over 100 replenishment methods
- PO is for unrecognized item-supplier combination
- DO is for unrecognized item-distribution combination

**Comment by hichamlahlou** [comment]
No Supplier : OK. Problem appearing in the problem report
101 suppliers : KO. No problem detected, and I personally agree with this, why would we limit the number of suppliers ?
PO with wrong item/supplier combination : OK, problem detected
DO with no item distribution declared : OK, problem detected

**Comment by jdetaeye** [comment]
Been bitten by too many alternates.   Had defined itemsupplier and itemdistributions records at a higher level, and accidentally ended up with an alternate with 16000 choices. Memory usuage and planning  time went up, and it wasn't easy to spot the root cause.  

I think that it's fair to say that if you have an alternate with > 100 choices there is very likely something wrong with the model...

**Comment by hichamlahlou** [comment]
ok I can get now the problem :
Excessive replenishments defined for ...
