### ISSUE TITLE
Change default installation folder in Windows

### ISSUE THREAD

**Issue by jdetaeye** [frePPLe/frePPLe#78]
The Windows installer creates files under   "C:\Users\X\AppData\Local\frePPLe\3.2".

More intuitive location is ""c:\program files\frepple\3.2"" for read-only install files + a user-independent location for all writable database data files and log files.

**Comment by jranita** [comment]
Tested on W2012 server.
If admin or user installs for himself -> all files on local appdata folder
If admin install for all users -> shared files go to c:\programdata\... and need to run pgsql as a service and django settings also needs the user set to the admin
