### ISSUE TITLE
Allow sorting on multiple columns in the reports

### ISSUE THREAD

**Issue by jdetaeye** [frePPLe/frepple#85]
- Jqgrid has multi-sort feature, easy
- Johan: backend changes to run matching SQL queries on the database as well, harder

**Comment by jdetaeye** [comment]
Backend queries are now multi-sort ready.

Jqgrid configuration is currently commented out, as the display is not very intuitive.
The oncolsort method needs updating to:
- display the order of the column sorted, with a small number next to the sort icon
- when adding a new column to the sort, the new column should be first in the list. Currently is added last.
- sometimes the sort icon is not displayed. Issue in our code or soemthing in jqgrid?

**Comment by jranita** [comment]
Number is now showing up.
The sort seems intuitive, except when you sorted several columns (sort 4 columns), clear the sorting from the last column sorted (column 1) and sort it again (column gets number 4).

**Comment by hichamlahlou** [comment]
To me, there are some problems still on this multi-column sorting.
First some tables appear to have a pre-defined sorting like demand which is always sorted by name when I first jump into it. If I try to deactivate the sorting, I press twice on the column title and there for instance the number remains there while the arrows have vanished :
![image](https://user-images.githubusercontent.com/14045225/27632088-f81c8148-5bfa-11e7-89ce-4d00b6054445.png)

**Comment by jdetaeye** [comment]
>>First some tables appear to have a pre-defined sorting...

That's a feature :-)     Eg the PO, DO, MO screen should be order by the inventory status by default.

>>If I try to deactivate the sorting, I press twice on the column title and there for instance the number remains there while the arrows have vanished :

That is a corner case to is easy to fix: after removing the last sort the number isn't removed

**Comment by jdetaeye** [comment]
Second issue seems to be a jqgrid issue on frozen columns.   Potentially non-trivial to fix

**Comment by jdetaeye** [comment]
Committed improved version
