### ISSUE TITLE
Enable forward planning mode with a parameter

### ISSUE THREAD

**Issue by jdetaeye** [frePPLe/frepple#87]
The planning algorithm does first a backward plan starting from the due date. When we find an order will be planned late, we switch to a forward planning mode where demands are planned as early as possible.

Some customer want to always plan in the forward scheduling mode.  We can easily do this by planning the demand as if its due date is already in the past.  
A parameter should allow a user to choose the correct mode.

**Comment by zipus** [comment]
Could you confirm this is by setting `plan.administrativeLeadtime` to 999?
There is no commit related with the issue.

**Comment by jdetaeye** [comment]
Yes, that's correct.
