### ISSUE TITLE
Unit test updates for the data model changes.

### ISSUE THREAD

**Issue by jdetaeye** [frePPLe/frePPLe#90]
- migrate engine unit tests
- update user interface tests

**Comment by jranita** [comment]
Cookbook tests ready... only failing on the calendar-working_hours test.
I am not sure about the resource-tool test, but it runs OK... do the "kanban cards" need to be included in item-operations?

**Comment by jdetaeye** [comment]
ready to add unit tests in tests UI + engine in both community & enterprise editions.  (skipping some specific engine tests)
