### ISSUE TITLE
exporting model as workbook exports hidden/excluded fields

### ISSUE THREAD

**Issue by jdetaeye** [frePPLe/frePPLe#94]
PO, MO and DO sheets contain fields that are not relevant for the record.

The fields are inherited from the operationplan model, but only a subset of the fields is valid for them.

**Comment by jranita** [comment]
In PO the PLAN field is ignored. MO and DO are failing to load a messed-up plan is not the reason... but again field ordering problems due to model changes.

**Comment by jranita** [comment]
Starting from a fresh migrate, rebuilding, run plan, export workbook, mess plan field, empty database, import workbook : field plan was ignored in PO, MO and DO.
